/* Writes build-info.js immediately before bundling.
   Two different questions were being conflated:
     "which RELEASE is this?"  -> package.json version, moved deliberately
     "which BUILD am I running?" -> changes on every deploy, automatically
   The founder saw the same version after several deploys and reasonably assumed
   the number was broken. It was not: semver should not move on every deploy.
   What was missing was a build identifier, so a tester report can be pinned to
   an exact bundle. This supplies it. */
import { writeFileSync } from "node:fs";
import { execSync } from "node:child_process";
import { readFileSync } from "node:fs";

const version = JSON.parse(readFileSync(new URL("./package.json", import.meta.url), "utf8")).version;

const git = (cmd, fallback) => {
  try { return execSync(cmd, { stdio: ["ignore", "pipe", "ignore"] }).toString().trim(); }
  catch { return fallback; }
};
const sha = git("git rev-parse --short HEAD", "nogit");
const dirty = git("git status --porcelain", "") !== "";
const built = new Date().toISOString().slice(0, 16).replace("T", " ");

writeFileSync(new URL("./build-info.js", import.meta.url),
`/* GENERATED by stamp.mjs on every build — do not edit, do not commit meaning to it. */
export const BUILD = ${JSON.stringify({ version, sha: sha + (dirty ? "+" : ""), built }, null, 1)};
`);
console.log("stamped " + version + " · " + sha + (dirty ? "+" : "") + " · " + built);
